version: 2

jobs:
    "node":
        docker:
            - image: circleci/python:3.7-node

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "demos/requirements.txt" }}

            - run:
                name: Create virtualenv
                command: |
                    python -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r requirements.txt --quiet
                    pip install -r demos/requirements.txt --quiet
                    pip install -r tests/requirements.txt --quiet

            - run:
                name: Install package.json
                command: |
                    . venv/bin/activate
                    npm i

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "demos/requirements.txt" }}
                paths:
                    - node_modules

            - run:
                name: Run eslint
                command: ./node_modules/.bin/eslint src
                when: always


    "python-3.6": &test-template
        docker:
            - image: circleci/python:3.6-stretch-browsers

        environment:
            PERCY_ENABLED: True

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "demos/requirements.txt" }}

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r demos/requirements.txt --quiet
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "demos/requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Run black
                command: |
                    . venv/bin/activate
                    black usage* --check
                    black demos --check
                    black tests --check
                when: always

            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    pytest tests
                when: always

            - store_artifacts:
                path: /tmp/dash_artifacts
                destination: snapshots

    "python-3.7":
        <<: *test-template
        docker:
            - image: circleci/python:3.7-stretch-browsers
        environment:
            PERCY_ENABLE: False


workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
            - "python-3.7"
            - "node"
